<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'RSVP Wedding Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'hannahdyoi@gmail.com',
		'to' => 'hannahdyoi@gmail.com'
	),
	'fields' => array(
		'custom_U107643' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Enter Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Enter Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Enter Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Enter Email\' is required.',
				'format' => 'Field \'Enter Email\' has an invalid email.'
			)
		),
		'custom_U107627' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Enter Phone Number',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U107623' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Talk on Marriage 
July 7, 2017 | 4:00pm',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U107637' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Wedding
July 8, 2017 | 1:30 PM',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U120499' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Home Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Address\' is required.'
			)
		),
		'custom_U177972' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Afternoon Tea (after wedding ceremony)
July 8, 2017 | 3:00 PM',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Afternoon Tea (after wedding ceremony)
July 8, 2017 | 3:00 PM\' is required.'
			)
		)
	)
);

process_form($form);
?>
